let DATA={items:[],batches:[],categories:[],suppliers:[]};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opt){let r=await fetch(url,opt);let d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function refreshAll(){try{let d=await api('/api/dashboard');let it=await api('/api/items');let ba=await api('/api/batches');DATA={...it,batches:ba.batches};$('statItems').textContent=it.items.length;$('statStock').textContent=fmt(d.total_stock);$('statLow').textContent=d.low_stock.length;$('statExpiry').textContent=d.expiry.length;renderAlerts(d);fillSelects();renderTables();loadReports()}catch(e){console.error(e)}}
function fmt(n){return Number(n||0).toLocaleString(undefined,{maximumFractionDigits:1})}
function renderAlerts(d){$('lowList').innerHTML=d.low_stock.length?d.low_stock.map(x=>`<div class="listItem"><span><b>${esc(x.name)}</b><br><small>${fmt(x.stock)} ${esc(x.unit)} available</small></span><span class="status low">Min ${fmt(x.min_stock)}</span></div>`).join(''):'<div class="muted">No low-stock items. Great!</div>';$('expiryList').innerHTML=d.expiry.length?d.expiry.slice(0,8).map(x=>`<div class="listItem"><span><b>${esc(x.item_name)}</b> · ${esc(x.batch_no)}<br><small>Expires ${esc(x.expiry_date)}</small></span><span class="status near">${fmt(x.remaining_qty)} ${esc(x.unit)}</span></div>`).join(''):'<div class="muted">No near-expiry batches.</div>'}
function fillSelects(){let opts=DATA.items.map(x=>`<option value="${x.id}">${esc(x.name)} (${fmt(x.stock)} ${esc(x.unit)})</option>`).join('');$('consumeItem').innerHTML=opts;$('wasteItem').innerHTML=opts;$('newCat').innerHTML=DATA.categories.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
function renderTables(){let q=$('search').value.toLowerCase(),f=$('filterStatus').value;let itemMap=Object.fromEntries(DATA.items.map(x=>[x.id,x]));let arr=DATA.batches.filter(b=>(`${b.item_name} ${b.batch_no} ${b.supplier_name||''}`).toLowerCase().includes(q));arr=arr.filter(b=>{let it=itemMap[b.item_id];let near=new Date(b.expiry_date)<=new Date(Date.now()+7*86400000);if(f==='low')return it&&it.stock<=it.min_stock;if(f==='expiry')return near;return true});$('batchTable').innerHTML=arr.map(b=>{let it=itemMap[b.item_id]||{};let near=new Date(b.expiry_date)<=new Date(Date.now()+7*86400000);let low=(it.stock||0)<=(it.min_stock||0);return `<tr><td><b>${esc(b.item_name)}</b><br><small>${esc(b.unit)}</small></td><td>${esc(b.batch_no)}</td><td>${esc(b.supplier_name||'—')}</td><td><b>${fmt(b.remaining_qty)}</b> ${esc(b.unit)}</td><td>${esc(b.purchase_date)}</td><td>${esc(b.expiry_date)}</td><td><span class="status ${near?'near':low?'low':'ok'}">${near?'Near expiry':low?'Low stock':'Healthy'}</span></td></tr>`}).join('')||'<tr><td colspan="7" class="muted">No matching batches.</td></tr>'}
async function consume(){try{let d=await api('/api/consume',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_id:$('consumeItem').value,quantity:$('consumeQty').value})});$('consumeResult').innerHTML='✓ FIFO used: '+d.used.map(x=>`${esc(x.batch_no)} (${fmt(x.quantity)})`).join(' + ');$('consumeQty').value='';refreshAll()}catch(e){$('consumeResult').textContent=e.message}}
async function waste(){try{await api('/api/wastage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_id:$('wasteItem').value,quantity:$('wasteQty').value,reason:$('wasteReason').value})});$('wasteResult').textContent='✓ Wastage recorded with batch traceability.';$('wasteQty').value='';$('wasteReason').value='';refreshAll()}catch(e){$('wasteResult').textContent=e.message}}
async function addItem(){try{await api('/api/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('newName').value,category_id:$('newCat').value,unit:$('newUnit').value,min_stock:$('newMin').value})});$('itemResult').textContent='✓ Item added.';$('newName').value='';refreshAll()}catch(e){$('itemResult').textContent=e.message}}
async function loadReports(){try{let d=await api('/api/reports');$('stockReport').innerHTML=d.stock.map(x=>`<tr><td>${esc(x.name)}</td><td>${fmt(x.stock)} ${esc(x.unit)}</td><td>${fmt(x.min_stock)}</td><td><span class="status ${x.stock<=x.min_stock?'low':'ok'}">${x.stock<=x.min_stock?'Low':'OK'}</span></td></tr>`).join('');$('purchaseReport').innerHTML=d.purchases.map(x=>`<tr><td>${esc(x.date)}</td><td>${x.batches}</td><td>₹${Number(x.value||0).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="3">No purchase data.</td></tr>';$('wasteReport').innerHTML=d.wastage.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.name)}</td><td>${fmt(x.quantity)}</td><td>${esc(x.reason)}</td></tr>`).join('')||'<tr><td colspan="4">No wastage recorded.</td></tr>'}catch(e){console.error(e)}}
function showLogin(){ $('modalContent').innerHTML=`<h2>Inventory Manager Login</h2><p class="muted">Demo credentials: <b>admin</b> / <b>admin123</b></p><label>Username<input id="loginUser" value="admin"></label><label>Password<input id="loginPass" type="password" value="admin123"></label><button class="btn" onclick="login()">Sign in</button><div id="loginResult" class="result"></div>`;$('modal').classList.add('show')}
async function login(){try{await api('/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('loginUser').value,password:$('loginPass').value})});$('userName').textContent='Admin';closeModal();alert('Login successful. FIFO operations are now enabled.')}catch(e){$('loginResult').textContent=e.message}}
function closeModal(){$('modal').classList.remove('show')}
function openBatch(){showLogin();$('modalContent').innerHTML=`<h2>Add Batch</h2><p class="muted">Login is required for protected inventory changes.</p><button class="btn" onclick="closeModal();location.hash='operations'">Go to Operations</button>`}
refreshAll();
